### ISSUE TITLE
[게시글 보기] 게시글 댓글 작성 이벤트

### ISSUE THREAD

**Issue by Hyun-SangYeop** [boostcampwm-2021/WEB13-JDevBook#13]
## 📢 이슈 내용
- 사용자는 게시글에서 [Comment]를 클릭하여 댓글을 작성할 수 있다.
## 📄 상세 내용
- 사용자는 게시글에서 [Comment]를 클릭하여 댓글을 작성할 수 있다.
## ✔ 체크리스트
- [ ] 사용자는 [Comment]를 클릭하여 다른 사람들의 댓글을 볼 수 있다.
- [ ] 사용자는 댓글 입력란에 글을 작성할 수 있다. (사진 첨부 등 불가능)
- [ ] 사용자는 댓글을 입력하면 댓글 삭제/수정을 할 수 없으니 유의해야 함

## 💾 참고 자료
- 기획서 : [기획서](https://paint-tip-6a6.notion.site/0c0c433f039a4c8ba47fddb48e016277)
- 백로그 : [백로그](https://docs.google.com/spreadsheets/d/1cgmO27IDYoLigAVKLopxEaJqVKHzibF5GTHeSaGBoKI/edit#gid=838702224)

**Comment by idiot-kitto** [comment]
나 아직 못했는..ㄷ...
