### ISSUE TITLE
[그룹 프로필 네비] Problems를 클릭하여 실행하는 문제 풀이 기능 구현

### ISSUE THREAD

**Issue by shinn338** [boostcampwm-2021/WEB13-JDevBook#26]
## 📢 이슈 내용
- [그룹 프로필 네비] Problems를 클릭하여 문제 풀이 기능 구현
## 📄 상세 내용
- 네비게이션에 위치하는 Problems 버튼을 클릭하여 해당 그룹의 문제 표시
- 네비게이션 하단에 위치하는 공간에 표시
## ✔ 체크리스트
- [x] API를 이용해 해당 그룹의 문제를 불러옴
- [ ] 무한 scroll bar 기능 추가
- [x] 푼 문제(맞춘 문제)는 표시
## 💾 참고 자료
- 기획서 : [기획서](https://paint-tip-6a6.notion.site/0c0c433f039a4c8ba47fddb48e016277)
- 백로그 : [백로그](https://docs.google.com/spreadsheets/d/1cgmO27IDYoLigAVKLopxEaJqVKHzibF5GTHeSaGBoKI/edit#gid=838702224)

**Comment by linear14** [comment]
무한스크롤 기능은 추가하지 않았습니다.
추후에 한 번에 불러올 문제수가 많아질 경우가 생긴다면 구현하도록 하겠습니다.
